### ISSUE TITLE
rename `@omi-wasm-group` discord group role [to `@omi-scripting-group`]

### ISSUE THREAD

**Issue by humbletim** [omigroup/omi-scripting-group#28]
this discord role is used for group notifications and was originally configured via "carlbot."

it's not entirely clear if we can simply rename the role in discord settings or if it has to be removed/recreated again using carlbot

**Comment by mrmetaverse** [comment]
@AdamFrisby @robertlong any risks with us switching the discord role? Will this break the bot? 

We are going to try it, but if it breaks we need to be prepared to fix the change. :sweat_smile:

**Comment by mrmetaverse** [comment]
No risks declared but this may break the bots association with the role. Made the change today. 

![Screenshot_20220505-073721.png](https://user-images.githubusercontent.com/63426722/166915776-11adc8c2-cc98-4753-9272-b76a14568bab.png)
