### ISSUE TITLE
sync Scripting Group => Developer Hour docs

### ISSUE THREAD

**Issue by humbletim** [omigroup/omi-scripting-group#30]
need to sync-up:
* [OMI main repo README.md](https://github.com/omigroup/omi-scripting-group/blob/main/README.md)
> ... this group Meets every Tuesday at 1500 UTC

* [OMI Google Calendar UTC](https://calendar.google.com/calendar/u/0/embed?src=c_0dpugf9f83eq4qekmb6omqbjmg@group.calendar.google.com&ctz=UTC)
> 1600 OMI Developer Hour

* [omi-scripting-group/README.md](https://github.com/omigroup/omi-scripting-group/blob/main/README.md)
> We host our weekly meetings live on Discord on Tuesdays from 1630 - 1700 UTC ...

**Comment by mrmetaverse** [comment]
I am transposing based on conversations. In an effort to promote github and the systems we have designed for this, I will paste here: 

1) do we have resources willing to help administrate subgroup?
  YES) proceed to next NO) dissolve
  
2) do we need to identify a better time to meet or will NN:NN work?
  YES) proceed to next NO) timevote
  
3) do we have a reliable way to keep people (community, presenters, etc.) informed of meeting go / no-go?
  YES) proceed to next NO) discuss options (who/what/when/how)?

I recommend adding votes to the channel. I am not a regularly attending member of the group, so I'd like to see someone who is create these votes in the channel on discord. If we can't find someone to do so, I am happy to create them.

**Comment by humbletim** [comment]
we've achieved sync on meeting time and general consensus now that as part of considering a more formal subgroup again we'll have to revisit administrative; for now plan is to keep alternating weeks between dev hours and scripting group meta discussion
