### ISSUE TITLE
Looking inward - next steps for and/or decoupling scripting group and developer HH

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omi-scripting-group#31]
I am transposing based on conversations. In an effort to promote github and the systems we have designed for this, I will paste here: 

1) do we have resources willing to help administrate subgroup?
  YES) proceed to next NO) dissolve
  
2) do we need to identify a better time to meet or will NN:NN work?
  YES) proceed to next NO) timevote
  
3) do we have a reliable way to keep people (community, presenters, etc.) informed of meeting go / no-go?
  YES) proceed to next NO) discuss options (who/what/when/how)?

I recommend adding votes to the channel. I am not a regularly attending member of the group, so I'd like to see someone who is create these votes in the channel on discord. If we can't find someone to do so, I am happy to create them.

_Originally posted by @mrmetaverse in https://github.com/omigroup/omi-scripting-group/issues/30#issuecomment-1175437686_

**Comment by mrmetaverse** [comment]
cc: @humbletim could you help me oversee this one? I don't want it to get lost in the sauce of the other tickets. :smile:

**Comment by robertlong** [comment]
I'm also in support of splitting out the developer hour from the scripting group. I'm still unsure if this proposed change is splitting scripting group into the developer hour and "platform implementors hour" talks and dissolving the scripting group as a formal working group or if this is just splitting out the developer hour into a separate effort, disconnected from the scripting group.

**Comment by AdamFrisby** [comment]
> I'm also in support of splitting out the developer hour from the scripting group. I'm still unsure if this proposed change is splitting scripting group into the developer hour and "platform implementors hour" talks and dissolving the scripting group as a formal working group or if this is just splitting out the developer hour into a separate effort, disconnected from the scripting group.

From my understanding, just splitting the developer/platform hour from the scripting hour. Scripting still has a significant amount of utility, but we are in some respects in limbo on the WASM front (pending our discussion 2 weeks from now)

**Comment by humbletim** [comment]
per #38 discussion -- humbletim to draft OMI readme.md pull request to consider as part of tomorrow's Wednesday community call (reflecting new meeting time and proposed conceptual separation of Developer Hour from Scripting/Platform Subgroup meetings)

**Comment by mrmetaverse** [comment]
This was discussed on Wednesday as mentioned above. Seems to be agreed upon that we should split the groups, now it looks like it's just the act of physically splitting that remains. Before I do that, I encourage you all to do the split of scripting group and dev hour. 

It is acknowledged on the readmes, anything else left to split? Need a repo or anything or can we move this to "done"? @humbletim (I don't want to be too assumptive that this is done)

**Comment by mrmetaverse** [comment]
done
